// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bammemo.Web.Client.WebApis.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetStorageTypeInfosResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The storageTypeInfos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bammemo.Web.Client.WebApis.Client.Models.StorageTypeInfoModel>? StorageTypeInfos { get; set; }
#nullable restore
#else
        public List<global::Bammemo.Web.Client.WebApis.Client.Models.StorageTypeInfoModel> StorageTypeInfos { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bammemo.Web.Client.WebApis.Client.Models.GetStorageTypeInfosResponse"/> and sets the default values.
        /// </summary>
        public GetStorageTypeInfosResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bammemo.Web.Client.WebApis.Client.Models.GetStorageTypeInfosResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bammemo.Web.Client.WebApis.Client.Models.GetStorageTypeInfosResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bammemo.Web.Client.WebApis.Client.Models.GetStorageTypeInfosResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "storageTypeInfos", n => { StorageTypeInfos = n.GetCollectionOfObjectValues<global::Bammemo.Web.Client.WebApis.Client.Models.StorageTypeInfoModel>(global::Bammemo.Web.Client.WebApis.Client.Models.StorageTypeInfoModel.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Bammemo.Web.Client.WebApis.Client.Models.StorageTypeInfoModel>("storageTypeInfos", StorageTypeInfos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
