name: Build Bammemo

on:
  push:
    branches: ['*']

  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [web] 
        include:
          - project: web
            dockerfile: ./src/Bammemo.Web/Bammemo.Web/Dockerfile
            image_name: huhubun/bammemo-web

    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ${{ matrix.dockerfile }} 
        push: false
        tags: ${{ env.REGISTRY }}/${{ matrix.image_name }}:ci-build
        target: build
