name: Build Bammemo

on:
  push:
    branches: ['*']

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      id: push
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./src/Bammemo.WebApi/Dockerfile
        push: false
        tags: |
          ci-build
        target: build
